version: '3.8'

services:
  app:
    image: node:16-alpine
    container_name: gwala-client
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3333:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "yarn install && yarn dev"
